# Generated by Django 4.2.3 on 2023-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0002_helptextmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helptextmedia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='boards/%Y/%m/%d/'),
        ),
    ]
