# Generated by Django 4.2.3 on 2023-07-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0003_alter_helptextmedia_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helptextmedia',
            name='img',
            field=models.ImageField(default=1, upload_to='boards/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
