# Generated by Django 4.2.3 on 2023-07-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tguser_father'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedBoardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.board')),
                ('tguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tguser')),
            ],
        ),
    ]
