# Generated by Django 4.2.3 on 2023-07-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_passedboardhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
