# Generated by Django 4.2.3 on 2023-07-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_present_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
