# Generated by Django 4.2.3 on 2023-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_board_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.IntegerField(unique=True),
        ),
    ]
