# Generated by Django 4.2.3 on 2023-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_board_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='name',
            field=models.CharField(default='wqq', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
