# Generated by Django 4.2.3 on 2023-07-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_present_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='tguser',
        ),
        migrations.AddField(
            model_name='present',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_usr', to='main.tguser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='present',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_usr', to='main.tguser'),
            preserve_default=False,
        ),
    ]
