# Generated by Django 4.2.3 on 2023-07-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_present_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedboardhistory',
            name='earn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
