# Generated by Django 4.2.3 on 2023-07-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_present_board_alter_present_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Join time'),
        ),
    ]
