# Generated by Django 4.2.3 on 2023-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_tguser_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='img',
            field=models.ImageField(default=1, upload_to='users/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='max_present_red',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
